### ISSUE TITLE
Old DH offered: no matching key exchange method found.

### ISSUE THREAD

**Issue by urban-1** [internap/fake-switches#159]
On more recent openssh setups `sha1` can be disabled. The error message when connecting to the fake_switch is

```
$ ssh root@localhost -p 2222
Unable to negotiate with 127.0.0.1 port 2222: no matching key exchange method found. Their offer: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1
```

A temp workaround is to allow sha1 with:

```
ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 root@localhost -p 2222
```

It would be nice if a more recent DH was supported. I have looked into twisted docs for a quick hack but I complete n00b in twisted and couldn't find a way to do this

---

Some part of my local ssh config:

```
$ ssh -V
OpenSSH_8.3p1, OpenSSL 1.1.1i FIPS  8 Dec 2020

$ ssh -G localhost
...
kexalgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
...
```

**Comment by simon-begin** [comment]
Hey.

If you need a fix right now you can look at this PR https://github.com/internap/fake-switches/pull/155. I didn't have the time to make sure that everything is working. But, it should work.

**Comment by urban-1** [comment]
Hi @simon-begin, thanks! Upping the requirement versions worked (but I tested with py36 and 38 - not 27)
