### ISSUE TITLE
Add the support for python 3

### ISSUE THREAD

**Issue by mbelang** [internap/fake-switches#80]

**Comment by stephanerobert** [comment]
I am working on it part time. The problem is not with fake-switches itself, but with the libraries we use.

**Comment by mat128** [comment]
https://caniusepython3.com/check/9eabee03-22ec-481e-90b8-8a1035d99c05

Only tftpy blocks us

**Comment by mat128** [comment]
Apparently progress is over there:
https://github.com/msoulier/tftpy/issues/54

**Comment by mat128** [comment]
and here: https://github.com/msoulier/tftpy/pull/69

**Comment by mat128** [comment]
Alternative:
https://pypi.python.org/pypi/minimumTFTP/20110917

**Comment by fbouliane** [comment]
@mat128 isshhh https://github.com/LossCuts/minimumTFTP

**Comment by mat128** [comment]
Yeah, only supports downloading to a file.

Interestingly enough, I found fbtftp, Facebook's TFTP daemon. Their test suite tests the daemon by using busybox:
https://github.com/facebook/fbtftp/blob/master/tests/integration_test.py#L57 and dumps to stdout. I wonder if we could just do that and list busybox as a dependency or something.

**Comment by mat128** [comment]
Otherwise, implementing the protocol yourself seems easy enough:
https://github.com/sirMackk/py3tftp/blob/master/tests/acceptance/rfc1350_test.py#L12
